### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by eherra** [bntti/tietokantasovellus#2]
Good looking and well-advanced project! Clearly can be seen that you have good SQL knowledge. (: Commits are small and informatively described, good!

Nice to see that you have on <code>.css</code> files take consideration different browsers adaptations! <code>.html</code> files organized neatly as well. No errors found on browser console while using the applicaton! 👍 

Small improvements which catch my eye:
- <code>.css</code> some boilerplate occurring e.g.  https://github.com/bntti/AnimeList/blob/main/static/profile.css#L5 
this could be refactored to: <code>
h3, p { margin-bottom: 5px; margin-top: 5px; }</code>
- are these methods used? https://github.com/bntti/AnimeList/blob/main/database.py#L20 (I would keep the database.py file clean and these methods to services)
- on “list” navigation page -> two times "submit changes" button https://github.com/bntti/AnimeList/blob/main/templates/list.html#L24 and https://github.com/bntti/AnimeList/blob/main/templates/list.html#L121
- client-side feedback would be nice for users after successful/unsuccessful operations e.g. when removing/updating something from the list. Flask has Flash feature which could do this. more from: https://flask.palletsprojects.com/en/2.0.x/patterns/flashing/

Good job!

**Comment by bntti** [comment]
Thank you for the review,
- I implemented three out of the four suggestions  
- `/list` view has two submit buttons because I think it is more convenient to have a submit button at the top of the page as well as at the bottom of the page if you have a long list.  
- The reason `.css` files take other browsers into consideration is that I copy-pasted code from StackOverflow :D
